services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: true
      MSSQL_SA_PASSWORD: sup3rSECRET!
    ports:
      - 1433:1433
    volumes:
      - database_data:/var/opt/mssql

volumes:
  database_data:
