services:
  # SQL Server 2022 Developer Edition
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: true
      MSSQL_SA_PASSWORD: sup3rSECRET!
    ports:
      - 1433:1433
    volumes:
      - database-data:/var/opt/mssql

  # Azure Storage Emulator
  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - storage-data:/data

volumes:
  database-data:
    driver: local
  storage-data:
    driver: local
