name: CI/CD Frontend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cicd-frontend.yml
      - frontend/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-frontend.yml
      - frontend/**
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        environment: ${{ github.ref_name == 'main' && fromJson('["prod", "test"]') || fromJson('["test"]') }}
    environment:
      name: ${{ matrix.environment }}
      url: ${{ matrix.environment == 'prod' && 'https://ratemy.pet' || 'https://test.ratemy.pet' }}

    steps:
      # Login to container registry
      - name: Login to container registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push image
      - name: Build and push image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          BUILD_CONFIGURATION: ${{ matrix.environment == 'prod' && 'production' || 'testing' }}
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          build-args: CONFIGURATION=${{ env.BUILD_CONFIGURATION }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ratemypet-web:latest
            ghcr.io/${{ github.repository_owner }}/ratemypet-web:${{ github.sha }}'
