name: CI/CD Backend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cicd-backend.yml
      - backend/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-backend.yml
      - backend/**
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    env:
      BUILD_CONFIGURATION: Release
      MIGRATIONS_SCRIPT: ${{ github.workspace }}/backend/migrations.sql
    defaults:
      run:
        working-directory: ${{ github.workspace }}/backend
    outputs:
      versionTag: ${{ steps.calc_tag.outputs.new_tag }}
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      # Install EF tool
      - name: Install EF tool
        run: dotnet tool install --global dotnet-ef

      # Restore packages
      - name: Restore packages
        run: dotnet restore

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      # Run tests
      - name: Run tests
        run: >-
          dotnet test
          --no-build
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --logger trx
          --collect "XPlat Code Coverage"
          --settings coverlet.runsettings

      # Publish test results
      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ${{ github.workspace }}/backend/tests/**/TestResults/*.trx
          check_name: Test results
          action_fail: true

      # Build migrations script
      - name: Build migrations script
        run: >-
          dotnet ef migrations script
          --no-build
          --idempotent
          --output ${{ env.MIGRATIONS_SCRIPT }}
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --project src/Infrastructure/Infrastructure.csproj
          --startup-project src/Api/Api.csproj

      # Upload migrations script
      - name: Upload migrations script
        uses: actions/upload-artifact@v4
        with:
          name: migrations
          path: ${{ env.MIGRATIONS_SCRIPT }}

      # Calculate next version
      - name: Calculate next version
        uses: anothrNick/github-tag-action@v1
        id: calc_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true
          PRERELEASE: ${{ github.ref != 'refs/heads/main' }}

      # Publish jobs project
      - name: Publish jobs project
        run: >-
          dotnet publish src/Jobs/Jobs.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --output ${{ github.workspace }}/jobs
          -p:Version=${{ steps.calc_tag.outputs.new_tag }}

      # Upload jobs artifact
      - name: Upload jobs artifact
        uses: actions/upload-artifact@v4
        with:
          name: jobs
          path: ${{ github.workspace }}/jobs
          include-hidden-files: true

  deploy:
    name: Deploy applications
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      packages: write
    strategy:
      matrix:
        environment: [test, prod]
    environment: ${{ matrix.environment }}
    steps:
      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to container registry
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push API image
      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          file: src/Api/Dockerfile
          push: true
          tags: |
            ghcr.io/frasermclean/ratemypet-api:latest
            ghcr.io/frasermclean/ratemypet-api:${{ needs.build.outputs.versionTag }}

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Download artifacts
      - name: Download artifacts
        id: download-artifacts
        uses: actions/download-artifact@v4

      # Deploy migrations script
      - name: Deploy migrations script
        uses: azure/sql-action@v2.3
        with:
          path: ${{ steps.download-artifacts.outputs.download-path }}/migrations/migrations.sql
          connection-string: ${{ secrets.DB_CONNECTION_STRING }}

      # Deploy API application
      - name: Deploy API application
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ghcr.io/frasermclean/ratemypet-api:${{ needs.build.outputs.versionTag }}
          containerAppName: ratemypet-${{ matrix.environment }}-api-ca
          resourceGroup: ratemypet-${{ matrix.environment }}-rg

      # Deploy jobs application
      - name: Deploy jobs application
        uses: Azure/functions-action@v1
        with:
          app-name: ratemypet-${{ matrix.environment }}-jobs-func
          package: ${{ steps.download-artifacts.outputs.download-path }}/jobs
