name: CI/CD Backend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cicd-backend.yml
      - backend/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-backend.yml
      - backend/**
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      BUILD_CONFIGURATION: Release
    defaults:
      run:
        working-directory: ${{ github.workspace }}/backend

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      # Restore packages
      - name: Restore packages
        run: dotnet restore

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      # Bump version and push tag
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag_commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push API image
      - name: Build and push API image
        if: github.event_name != 'pull_request'
        run: >-
          dotnet publish src/Api/Api.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          -p:PublishProfile=DefaultContainer
          -p:Version=${{ steps.tag_commit.outputs.new_tag }}
          -p:ContainerRegistry=ghcr.io
          -p:ContainerRepository=${{ vars.API_REPOSITORY_NAME}}
