name: CI/CD Backend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cicd-backend.yml
      - backend/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-backend.yml
      - backend/**
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release
    defaults:
      run:
        working-directory: ${{ github.workspace }}/backend

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      # Restore packages
      - name: Restore packages
        run: dotnet restore

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

  deploy:
    name: Deploy application
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Bump version and push tag
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag_commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true

      # Deploy Container App
      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/backend
          dockerfilePath: api.Dockerfile
          imageToBuild: ghcr.io/${{ vars.API_REPOSITORY_NAME }}:${{ steps.tag_commit.outputs.tag }}
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}
          containerAppName: ${{ vars.API_CONTAINER_APP_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
