name: CI/CD Frontend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cicd-frontend.yml
      - frontend/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-frontend.yml
      - frontend/**
    types:
      - opened
      - synchronize
      - reopened

env:
  APP_ARTIFACT_NAME: app

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/frontend

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build application
      - name: Build application
        env:
          BUILD_CONFIGURATION: ${{ github.event_name == 'pull_request' && 'testing' || 'production' }}
        run: npx ng build --configuration ${{ env.BUILD_CONFIGURATION }}

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_ARTIFACT_NAME }}
          path: ${{ github.workspace }}/frontend/dist/browser

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'prod' || 'test' }}
    steps:
      # Download artifact
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_ARTIFACT_NAME }}

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
          app_location: ${{ steps.download-artifact.outputs.download-path }}
          skip_app_build: true
          skip_api_build: true
