name: CI/CD Backend

on:
  push:
    branches:
      - main
      - feature/jobs-azure-functions
    paths:
      - .github/workflows/cicd-backend.yml
      - backend/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-backend.yml
      - backend/**
    types:
      - opened
      - synchronize
      - reopened

env:
  CONTAINER_REGISTRY: ghcr.io
  API_IMAGE_REPOSITORY: frasermclean/ratemypet-api

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      BUILD_CONFIGURATION: Release
    defaults:
      run:
        working-directory: ${{ github.workspace }}/backend
    outputs:
      versionTag: ${{ steps.calc_tag.outputs.new_tag }}

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      # Restore packages
      - name: Restore packages
        run: dotnet restore

      # Build solution
      - name: Build solution
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      # Calculate next version
      - name: Calculate next version
        uses: anothrNick/github-tag-action@v1
        if: github.event_name != 'pull_request'
        id: calc_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          DRY_RUN: true

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push API image
      - name: Build and push API image
        if: github.event_name != 'pull_request'
        run: >-
          dotnet publish src/Api/Api.csproj
          --configuration ${{ env.BUILD_CONFIGURATION }}
          -p:PublishProfile=DefaultContainer
          -p:Version=${{ steps.calc_tag.outputs.new_tag }}
          -p:ContainerRegistry=${{ env.CONTAINER_REGISTRY }}
          -p:ContainerRepository=${{ env.API_IMAGE_REPOSITORY }}

      # Publish jobs project
      - name: Publish jobs project
        if: github.event_name != 'pull_request'
        run: >-
          dotnet publish src/Adoptrix.Jobs
          --no-build
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --output ${{ github.workspace }}/jobs

      # Upload jobs artifact
      - name: Upload jobs artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: jobs
          path: ${{ github.workspace }}/jobs

  deploy:
    name: Deploy application
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Container App
      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.CONTAINER_REGISTRY }}/${{ env.API_IMAGE_REPOSITORY }}:${{ needs.build.outputs.versionTag }}
          containerAppName: ${{ vars.API_CONTAINER_APP_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}

      # Update version tag
      - name: Update version tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ needs.build.outputs.versionTag }}
