name: CI/CD Frontend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cicd-frontend.yml
      - frontend/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cicd-frontend.yml
      - frontend/**
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod, test]
    defaults:
      run:
        working-directory: ${{ github.workspace }}/frontend

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build application
      - name: Build application
        run: npx ng build --configuration ${{ matrix.environment == 'prod' && 'production' || 'testing' }}

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.environment }}
          path: ${{ github.workspace }}/frontend/dist/browser

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: [prod, test]
    environment: ${{ matrix.environment }}
    steps:
      # Download artifact
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ matrix.environment }}

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
          app_location: ${{ steps.download-artifact.outputs.download-path }}
          skip_app_build: true
          skip_api_build: true
