name: Deploy infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to deploy to
        required: true

jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Remove Bicep configuration file (to remove experimental warning)
      - name: Remove Bicep configuration file
        run: rm ${{ github.workspace }}/deploy/bicepconfig.json

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy shared resources
      - name: Deploy shared resources
        uses: azure/arm-deploy@v2
        id: deploy_shared
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.SHARED_RESOURCE_GROUP }}
          template: ${{ github.workspace }}/deploy/shared/main.bicep
          parameters: ${{ github.workspace }}/deploy/shared/main.bicepparam

      # Deploy app resources
      - name: Deploy app resources
        uses: azure/arm-deploy@v2
        id: deploy_app
        with:
          scope: resourcegroup
          resourceGroupName: ratemypet-${{ inputs.environment }}-rg
          template: ${{ github.workspace }}/deploy/apps/main.bicep
          parameters: >-
            ${{ github.workspace }}/deploy/apps/main.${{ inputs.environment }}.bicepparam
            sharedResourceGroup=${{ vars.SHARED_RESOURCE_GROUP }}
            keyVaultName=${{ steps.deploy_shared.outputs.keyVaultName }}
            appConfigurationName=${{ steps.deploy_shared.outputs.appConfigurationName }}

      # Grant API app database access
      - name: Grant API app database access
        shell: pwsh
        run: >-
          ${{ github.workspace }}/deploy/scripts/Grant-DbAccess.ps1
          -PrincipalName ${{ steps.deploy_app.outputs.apiAppName }}
          -ConnectionString ${{ secrets.DB_CONNECTION_STRING }}

      # Grant jobs app database access
      - name: Grant jobs app database access
        shell: pwsh
        run: >-
          ${{ github.workspace }}/deploy/scripts/Grant-DbAccess.ps1
          -PrincipalName ${{ steps.deploy_app.outputs.jobsAppName }}
          -ConnectionString ${{ secrets.DB_CONNECTION_STRING }}
