name: Deploy EF Migrations

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: The environment to deploy to
        required: true
      artifact-name:
        type: string
        description: The name of the artifact containing the migrations script
        default: migrations
      script-name:
        type: string
        description: The name of the script to deploy
        default: migrations.sql

jobs:
  deploy:
    name: Deploy migrations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    steps:
      # Download artifact
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy migrations script
      - name: Deploy migrations script
        uses: azure/sql-action@v2.3
        env:
          CONNECTION_STRING: >-
            Server=tcp:ratemypet-${{ inputs.environment }}-sql.database.windows.net,1433;
            Initial Catalog=ratemypet-${{ inputs.environment }}-sqldb;
            Encrypt=True;
            TrustServerCertificate=False;
            Connection Timeout=30;
            Authentication=Active Directory Default;
        with:
          path: ${{ steps.download-artifact.outputs.download-path }}/${{ inputs.script-name }}
          connection-string: ${{ env.CONNECTION_STRING }}
