name: Deploy EF Migrations

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/migrations-deployment
    paths:
      - .github/workflows/deploy-migrations.yml
      - backend/src/Infrastructure/Migrations/**

jobs:
  deploy:
    name: Deploy migrations
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
    env:
      BUILD_CONFIGURATION: Release
    defaults:
      run:
        working-directory: ${{ github.workspace }}/backend
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha}}

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      # Install EF tool
      - name: Install EF tool
        run: dotnet tool install --global dotnet-ef

      # Build migrations bundle
      - name: Build migrations bundle
        run: >-
          dotnet ef migrations bundle
          --configuration ${{ env.BUILD_CONFIGURATION }}
          --project src/Infrastructure/Infrastructure.csproj
          --startup-project src/Api/Api.csproj

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Get runner IP address
      - name: Get runner IP address
        run: |
          RUNNER_IP="$(curl --silent https://api.ipify.org)"
          echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV

      # Allow runner IP address
      - name: Allow runner IP address
        run: >-
          az sql server firewall-rule create
          --name allow-runner-rule
          --server ratemypet-prod-sql
          --resource-group ratemypet-prod-rg
          --start-ip-address $RUNNER_IP
          --end-ip-address $RUNNER_IP

      # Remove runner rule
      - name: Remove runner rule
        run: >-
          az sql server firewall-rule delete
          --name allow-runner-rule
          --server ratemypet-prod-sql
          --resource-group ratemypet-prod-rg
